### PR TITLE
Add support for custom Job and Deployment IDs

### PR DESCRIPTION
**Pull request by mhaas**
This commit adds support for custom Job and Deployment IDs to be
passed to the Data Attribute Recommendation service when creating
the respective Job or Deployments.

This change is not generally available in the service, but the SDK
supports it already.

Additionally, this PR updates all dependencies and checks to latest
along with any fixes required by these updates.

### CODE REVIEW

**Review by karthikmswamy — APPROVED** [review]
Pretty cool! The SDK is just getting better by the day. Thanks a lot for that!

**Comment by karthikmswamy** [comment]
Looks like the Python 3.5 build failed: https://travis-ci.com/github/SAP/data-attribute-recommendation-python-sdk/jobs/513032457

**Comment by mhaas** [comment]
Hi @karthikmswamy, thanks for checking the build! Python 3.5 is now EOL. I have fixed the build for now. At the same time, I have added a deprecation notice that 3.5 support will be removed eventually.

**Comment by karthikmswamy** [comment]
Thanks for the update, @mhaas! Sounds good to me :)

**Pull request merged**
